name: Build and Deploy
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --configuration production --base-href=https://labchsl.com/

      - name: Deploy to prod-app branch
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: prod-app
          folder: public
