name: Build and Deploy
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --configuration production --base-href=/
        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Deploy 🚀
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: prod-app
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          external_repository: LuisDaniel90/app-angular
          enable_jekyll: true
          user_name: 'PlayTIC'
          user_email: 'f3rjara@gmail.com'
          commit_message: 'Deploying to prod-app'
