name: Build and Deploy
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --configuration production --base-href=/

      - name: Checkout to prod-app branch
        run: |
          git checkout -b prod-app
          git add -f public/
          git commit -m "Build for prod to prod-app branch"
          git push origin prod-app
