name: Build and Deploy
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --configuration production --base-href=/

      - name: Construccion to prod-app branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "ldanielcabreral@gmail.com"
          git config user.name "PlayTIC"
          git checkout -b prod-app
          git rm -r --cached .
          git clean -df
          cp -r public/* .
          git add -A
          git commit -m "Build for prod to prod-app branch"
          git push origin prod-app

